# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shopping.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eshopping.proto\x12\x08shopping\"\x9a\x01\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x1a\n\x12quantity_remaining\x18\x06 \x01(\x05\x12\x16\n\x0eseller_address\x18\x07 \x01(\t\x12\x0e\n\x06rating\x18\x08 \x01(\x02\"A\n\x19SellerRegistrationRequest\x12\x16\n\x0eseller_address\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"-\n\x1aSellerRegistrationResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"9\n\x12\x42uyerSearchRequest\x12\x11\n\titem_name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\"K\n\x0f\x42uyerBuyRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x15\n\rbuyer_address\x18\x03 \x01(\t\">\n\x14\x42uyerWishlistRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x15\n\rbuyer_address\x18\x02 \x01(\t\"J\n\x10\x42uyerRateRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\x12\x15\n\rbuyer_address\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x05\x32\xba\x02\n\x06Market\x12[\n\x0eRegisterSeller\x12#.shopping.SellerRegistrationRequest\x1a$.shopping.SellerRegistrationResponse\x12*\n\x08SellItem\x12\x0e.shopping.Item\x1a\x0e.shopping.Item\x12,\n\nUpdateItem\x12\x0e.shopping.Item\x1a\x0e.shopping.Item\x12,\n\nDeleteItem\x12\x0e.shopping.Item\x1a\x0e.shopping.Item\x12K\n\x12\x44isplaySellerItems\x12#.shopping.SellerRegistrationRequest\x1a\x0e.shopping.Item0\x01\x32\xf4\x01\n\x05\x42uyer\x12<\n\nSearchItem\x12\x1c.shopping.BuyerSearchRequest\x1a\x0e.shopping.Item0\x01\x12\x34\n\x07\x42uyItem\x12\x19.shopping.BuyerBuyRequest\x1a\x0e.shopping.Item\x12?\n\rAddToWishList\x12\x1e.shopping.BuyerWishlistRequest\x1a\x0e.shopping.Item\x12\x36\n\x08RateItem\x12\x1a.shopping.BuyerRateRequest\x1a\x0e.shopping.Itemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shopping_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ITEM']._serialized_start=29
  _globals['_ITEM']._serialized_end=183
  _globals['_SELLERREGISTRATIONREQUEST']._serialized_start=185
  _globals['_SELLERREGISTRATIONREQUEST']._serialized_end=250
  _globals['_SELLERREGISTRATIONRESPONSE']._serialized_start=252
  _globals['_SELLERREGISTRATIONRESPONSE']._serialized_end=297
  _globals['_BUYERSEARCHREQUEST']._serialized_start=299
  _globals['_BUYERSEARCHREQUEST']._serialized_end=356
  _globals['_BUYERBUYREQUEST']._serialized_start=358
  _globals['_BUYERBUYREQUEST']._serialized_end=433
  _globals['_BUYERWISHLISTREQUEST']._serialized_start=435
  _globals['_BUYERWISHLISTREQUEST']._serialized_end=497
  _globals['_BUYERRATEREQUEST']._serialized_start=499
  _globals['_BUYERRATEREQUEST']._serialized_end=573
  _globals['_MARKET']._serialized_start=576
  _globals['_MARKET']._serialized_end=890
  _globals['_BUYER']._serialized_start=893
  _globals['_BUYER']._serialized_end=1137
# @@protoc_insertion_point(module_scope)
